### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
#All OK

**Comment by python3lover** [comment]
# All OK

**Comment by ghost** [comment]
# All OK

**Comment by python3lover** [comment]
@html5lover, if you stop spamming, I will grant you write access.

**Comment by ghost** [comment]
ok sure

**Comment by python3lover** [comment]
# Locking Pull Request

**Comment by python3lover** [comment]
# Locking Pull Request (10s)

**Comment by python3lover** [comment]
# Locking Pull Request (in 10s)

**Comment by python3lover** [comment]
# Locking Pull Request (5s)

**Comment by ghost** [comment]
I'm not Spamming

**Comment by ghost** [comment]
you are

**Comment by python3lover** [comment]
# Locking Pull Request

**Pull request merged**
